services:
  php:
    build: ./docker/php
    volumes:
      - ./src:/var/www/html
      - ./data:/var/www/data
    networks:
      - app

  nginx:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/public:/var/www/html/public
    depends_on:
      - php
    networks:
      - app

networks:
  app:
    driver: bridge